// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtabdcuuxdohoexijgtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0YWJkY3V1eGRvaG9leGlqZ3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDc2NDMsImV4cCI6MjA2MDkyMzY0M30.FYkYZgiWVzaS8-vRz7aw0PwXCGaOhuaGYO1szA1hPn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);